Dockerfile
Quick PR to update the Dockerfile to match the latest version of n8n.
=> Update n8n to 0.156.0

config.json
Sorry - another PR. Supervisor doesn't yet detect that there's a new version. Bumping the version number should do that afaik!
=> Bump version number in config.json

Dockerfile
=> Update n8n to 0.205.0

Dockerfile, config.json
=> Update n8n to 0.206.1

Dockerfile, config.json
=> Update n8n to 0.208.1

Dockerfile, config.json
=> Update n8n to 0.209.0

README.md, config.json, docker-entrypoint.sh
=> feat(n8n): Add an env var to be able to set the instance URL for callbacks and webhooks

Dockerfile, config.json
=> Update n8n to 0.210.2

Dockerfile, config.json
=> Update n8n to 0.211.1

Dockerfile, config.json
=> Update n8n to 0.212.0

Dockerfile, config.json
=> Update n8n to 0.213.0

Dockerfile, config.json
=> Update n8n to 0.214.1

Dockerfile, config.json
=> Update n8n to 0.215.1

Dockerfile, config.json
=> Update n8n to 0.219.1

Dockerfile, config.json
=> Update n8n to 0.220.0

Dockerfile, config.json
=> Update n8n to 0.221.2

Dockerfile, config.json
=> Update n8n to 0.223.0

Dockerfile, config.json
=> Update n8n to 0.224.1

Dockerfile, config.json
=> Update n8n to 0.225.1

Dockerfile, config.json
=> Update n8n to 0.226.0

config.json
=> feat: Add backup mount to the plugin

Dockerfile, config.json
=> Update n8n to 0.227.0

Dockerfile, config.json
=> Update n8n to 0.228.2

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 0.230.0

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 0.230.1

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 0.231.0

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 0.232.0

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 0.235.0

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 0.236.0

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 0.236.3

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 0.237.0

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.8.2

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.9.3

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.11.2

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.14.2

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.15.2

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.16.0

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.17.1

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.22.4

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.22.6

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.24.1

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.25.1

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.26.0

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.27.2

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.27.3

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.29.1

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.31.2

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.32.2

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.33.1

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.34.2

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.36.4

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.37.3

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.38.2

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.39.1

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.42.1

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.44.1

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.45.1

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.47.2

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.49.0

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.51.1

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.52.2

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.54.4

CHANGELOG.md, Dockerfile, config.json
=> Update n8n to 1.55.3

CHANGELOG.md, config.json
=> Update n8n to 1.66.0

CHANGELOG.md, config.json
=> Update n8n to 1.67.1

CHANGELOG.md, config.json
=> Update n8n to 1.69.0

CHANGELOG.md, config.json
=> Update n8n to 1.70.0

CHANGELOG.md, config.json
=> Update n8n to 1.70.1

CHANGELOG.md, config.json
=> Update n8n to 1.71.1

CHANGELOG.md, config.json
=> Update n8n to 1.72.1

CHANGELOG.md, config.json
=> Update n8n to 1.73.1

CHANGELOG.md, config.json
=> Update n8n to 1.74.1

CHANGELOG.md, config.json
=> Update n8n to 1.75.2

CHANGELOG.md, config.json
=> Update n8n to 1.76.1

CHANGELOG.md, config.json
=> Update n8n to 1.80.2

CHANGELOG.md, config.json
=> Update n8n to 1.80.3

CHANGELOG.md, config.json
=> Update n8n to 1.81.0

CHANGELOG.md, config.json
=> Update n8n to 1.81.1

CHANGELOG.md, config.json
=> Update n8n to 1.81.2

config.json, docker-entrypoint.sh
=> fix: properly revert ingress

CHANGELOG.md, config.json
=> chore: update changelog for release 3.3.1

CHANGELOG.md, config.json
=> chore: update changelog for release 3.3.2

CHANGELOG.md, config.json
=> chore: update changelog for release 3.3.3

CHANGELOG.md, config.json
=> chore: update changelog for release 3.3.4

CHANGELOG.md, config.json
=> chore: update changelog for release 3.3.5

CHANGELOG.md, config.json
=> chore: update changelog for release 3.3.7

CHANGELOG.md, config.json
=> chore: update changelog for release 3.3.8

CHANGELOG.md, config.json
=> chore: update changelog for release 3.3.9

CHANGELOG.md, config.json
=> chore: update changelog for release 3.4.1

CHANGELOG.md, config.json
=> chore: update changelog for release 3.4.2

CHANGELOG.md, config.json
=> chore: update changelog for release 3.4.3

CHANGELOG.md, config.json
=> chore: update changelog for release 3.4.5

CHANGELOG.md
=> chore: update changelog for release 3.5.0

CHANGELOG.md, config.json
=> chore: update changelog for release 3.4.9

CHANGELOG.md, config.json
=> chore: update changelog for release 4.0.0

CHANGELOG.md, config.json
=> chore: update changelog for release 4.0.1

CHANGELOG.md, config.json
=> chore: update changelog for release 4.0.2

CHANGELOG.md, config.json
=> chore: update changelog for release 4.0.5

CHANGELOG.md, config.json
=> chore: update changelog for release 4.0.6

CHANGELOG.md, config.json
=> chore: update changelog for release 4.0.7

CHANGELOG.md, config.json
=> chore: update changelog for release 4.0.10

CHANGELOG.md, config.json
=> chore: update changelog for release 4.0.11

CHANGELOG.md, config.json
=> chore: update changelog for release 4.0.12

CHANGELOG.md, config.json
=> chore: update changelog for release 4.0.13

nginx.conf
=> fix: connection lost issue due to invalid origin

CHANGELOG.md, config.json
=> chore: update changelog for release 4.0.14

CHANGELOG.md, config.json
=> chore: update changelog for release 4.1.0

CHANGELOG.md, config.json
=> chore: update changelog for release 4.1.2

CHANGELOG.md, config.json
=> chore: update changelog for release 4.2.1

CHANGELOG.md, config.json
=> chore: update changelog for release 4.2.3

CHANGELOG.md, config.json
=> chore: update changelog for release 4.2.4

CHANGELOG.md, config.json
=> chore: update changelog for release 4.2.6

CHANGELOG.md, config.json
=> chore: update changelog for release 4.2.7

CHANGELOG.md, config.json
=> chore: update changelog for release 4.2.10

CHANGELOG.md, config.json
=> chore: update changelog for release 4.2.13

CHANGELOG.md, config.json
=> chore: update changelog for release 4.2.14

CHANGELOG.md, config.json
=> chore: update changelog for release 4.2.15
